package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Wed Jun 10 10:28:16 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    /**
    * 查询所有的数据字典类型
    */
    List<DicType> selectAllDicTypes();

    /**
    * 根据code查询数据字典类型
    */
    DicType selectDicTypeByCode(String code);

    /**
    * 保存创建的数据字典类型
    */
    int insertDicType(DicType dicType);

    /**
    * 根据code数组批量删除数据字典类型
    */
    int deleteDicTypeByCodes(String[] codes);

    /**
    * 保存更新的数据字典类型
    */
    int updateDicType(DicType dicType);
}