package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.domain.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    int insert(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    int insertSelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    int updateByPrimaryKeySelective(DicValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbggenerated Sat Jun 13 09:47:32 CST 2020
     */
    int updateByPrimaryKey(DicValue record);

    /**
    * 查询所有的数据字典值
    */
    List<DicValue> selectAllDicValues();

    /**
    * 保存创建的数据字典值
    */
    int insertDicValue(DicValue dicValue);

    /**
    * 根据ids批量删除数据字典值
    */
    int deleteDicValueByIds(String[] ids);

    /**
    * 根据id查询数据字典值
    */
    DicValue selectDicValueById(String id);

    /**
    * 保存修改的数据字典值
    */
    int updateDicValue(DicValue dicValue);
    
    /**
    * 根据typeCodes批量删除这些类型下所有的数据字典值
    */
    int deleteDicValueByTypeCode(String[] typeCodes);

    /**
    * 根据typeCode查询数据字典值
    */
    List<DicValue> selectDicValueByTypeCode(String typeCode);
}